# Generated by Django 3.2.14 on 2023-03-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='flag',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='data',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
